// Generated by generate.js — do not edit by hand.
const PACKAGES = [
  {
    "name": "R6",
    "path": "images/R6.svg",
    "url": "https://r6.r-lib.org"
  },
  {
    "name": "RStudio",
    "path": "images/RStudio.svg",
    "url": "https://posit.co/products/open-source/rstudio/"
  },
  {
    "name": "agua",
    "path": "images/agua.svg",
    "url": "https://agua.tidymodels.org"
  },
  {
    "name": "air",
    "path": "images/air.svg",
    "url": "https://posit-dev.github.io/air/"
  },
  {
    "name": "applicable",
    "path": "images/applicable.svg",
    "url": "https://applicable.tidymodels.org"
  },
  {
    "name": "ark",
    "path": "images/ark.svg",
    "url": "https://github.com/posit-dev/ark"
  },
  {
    "name": "baguette",
    "path": "images/baguette.svg",
    "url": "https://baguette.tidymodels.org"
  },
  {
    "name": "blastula",
    "path": "images/blastula.svg",
    "url": "https://rstudio.github.io/blastula/"
  },
  {
    "name": "blogdown",
    "path": "images/blogdown.svg",
    "url": "https://rstudio.github.io/blogdown/"
  },
  {
    "name": "bonsai",
    "path": "images/bonsai.svg",
    "url": "https://bonsai.tidymodels.org"
  },
  {
    "name": "bookdown",
    "path": "images/bookdown.svg",
    "url": "https://rstudio.github.io/bookdown/"
  },
  {
    "name": "broom",
    "path": "images/broom.svg",
    "url": "https://broom.tidyverse.org"
  },
  {
    "name": "bslib",
    "path": "images/bslib.svg",
    "url": "https://rstudio.github.io/bslib/"
  },
  {
    "name": "butcher",
    "path": "images/butcher.svg",
    "url": "https://butcher.tidymodels.org"
  },
  {
    "name": "censored",
    "path": "images/censored.svg",
    "url": "https://censored.tidymodels.org"
  },
  {
    "name": "chattr",
    "path": "images/chattr.svg",
    "url": "https://mlverse.github.io/chattr/"
  },
  {
    "name": "chromote",
    "path": "images/chromote.svg",
    "url": "https://rstudio.github.io/chromote/"
  },
  {
    "name": "clock",
    "path": "images/clock.svg",
    "url": "https://clock.r-lib.org"
  },
  {
    "name": "connectapi",
    "path": "images/connectapi.svg",
    "url": "https://pkgs.rstudio.com/connectapi/"
  },
  {
    "name": "connections",
    "path": "images/connections.svg",
    "url": "https://rstudio.github.io/connections/"
  },
  {
    "name": "corrr",
    "path": "images/corrr.svg",
    "url": "https://corrr.tidymodels.org"
  },
  {
    "name": "covr",
    "path": "images/covr.svg",
    "url": "https://covr.r-lib.org"
  },
  {
    "name": "dbplot",
    "path": "images/dbplot.svg",
    "url": "https://edgararuiz.github.io/dbplot/"
  },
  {
    "name": "dbplyr",
    "path": "images/dbplyr.svg",
    "url": "https://dbplyr.tidyverse.org"
  },
  {
    "name": "debrief",
    "path": "images/debrief.svg",
    "url": "https://r-lib.github.io/debrief/"
  },
  {
    "name": "devtools",
    "path": "images/devtools.svg",
    "url": "https://devtools.r-lib.org"
  },
  {
    "name": "dials",
    "path": "images/dials.svg",
    "url": "https://dials.tidymodels.org"
  },
  {
    "name": "discrim",
    "path": "images/discrim.svg",
    "url": "https://discrim.tidymodels.org"
  },
  {
    "name": "distill",
    "path": "images/distill.svg",
    "url": "https://rstudio.github.io/distill/"
  },
  {
    "name": "dplyr",
    "path": "images/dplyr.svg",
    "url": "https://dplyr.tidyverse.org"
  },
  {
    "name": "dsbox",
    "path": "images/dsbox.svg",
    "url": "https://datasciencebox.org"
  },
  {
    "name": "dtplyr",
    "path": "images/dtplyr.svg",
    "url": "https://dtplyr.tidyverse.org"
  },
  {
    "name": "duckplyr",
    "path": "images/duckplyr.svg",
    "url": "https://duckplyr.tidyverse.org"
  },
  {
    "name": "ellmer",
    "path": "images/ellmer.svg",
    "url": "https://ellmer.tidyverse.org"
  },
  {
    "name": "embed",
    "path": "images/embed.svg",
    "url": "https://embed.tidymodels.org"
  },
  {
    "name": "farver",
    "path": "images/farver.svg",
    "url": "https://farver.data-imaginist.com"
  },
  {
    "name": "feather",
    "path": "images/feather.svg",
    "url": "https://github.com/wesm/feather"
  },
  {
    "name": "filtro",
    "path": "images/filtro.svg",
    "url": "https://filtro.tidymodels.org"
  },
  {
    "name": "finetune",
    "path": "images/finetune.svg",
    "url": "https://finetune.tidymodels.org"
  },
  {
    "name": "flexdashboard",
    "path": "images/flexdashboard.svg",
    "url": "https://rstudio.github.io/flexdashboard/"
  },
  {
    "name": "forcats",
    "path": "images/forcats.svg",
    "url": "https://forcats.tidyverse.org"
  },
  {
    "name": "fs",
    "path": "images/fs.svg",
    "url": "https://fs.r-lib.org"
  },
  {
    "name": "furrr",
    "path": "images/furrr.svg",
    "url": "https://furrr.futureverse.org"
  },
  {
    "name": "gganimate",
    "path": "images/gganimate.svg",
    "url": "https://gganimate.com"
  },
  {
    "name": "ggplot2",
    "path": "images/ggplot2.svg",
    "url": "https://ggplot2.tidyverse.org"
  },
  {
    "name": "glue",
    "path": "images/glue.svg",
    "url": "https://glue.tidyverse.org"
  },
  {
    "name": "googledrive",
    "path": "images/googledrive.svg",
    "url": "https://googledrive.tidyverse.org"
  },
  {
    "name": "googlesheets",
    "path": "images/googlesheets.svg",
    "url": "https://github.com/jennybc/googlesheets"
  },
  {
    "name": "googlesheets4",
    "path": "images/googlesheets4.svg",
    "url": "https://googlesheets4.tidyverse.org"
  },
  {
    "name": "great_tables",
    "path": "images/great_tables.svg",
    "url": "https://posit-dev.github.io/great-tables/"
  },
  {
    "name": "gt",
    "path": "images/gt.svg",
    "url": "https://gt.rstudio.com"
  },
  {
    "name": "gtable",
    "path": "images/gtable.svg",
    "url": "https://gtable.r-lib.org"
  },
  {
    "name": "hardhat",
    "path": "images/hardhat.svg",
    "url": "https://hardhat.tidymodels.org"
  },
  {
    "name": "haven",
    "path": "images/haven.svg",
    "url": "https://haven.tidyverse.org"
  },
  {
    "name": "hms",
    "path": "images/hms.svg",
    "url": "https://hms.tidyverse.org"
  },
  {
    "name": "htmltools",
    "path": "images/htmltools.svg",
    "url": "https://rstudio.github.io/htmltools/"
  },
  {
    "name": "httr2",
    "path": "images/httr2.svg",
    "url": "https://httr2.r-lib.org"
  },
  {
    "name": "infer",
    "path": "images/infer.svg",
    "url": "https://infer.tidymodels.org"
  },
  {
    "name": "keras3",
    "path": "images/keras3.svg",
    "url": "https://keras.posit.co"
  },
  {
    "name": "knitr",
    "path": "images/knitr.svg",
    "url": "https://yihui.org/knitr/"
  },
  {
    "name": "lintr",
    "path": "images/lintr.svg",
    "url": "https://lintr.r-lib.org"
  },
  {
    "name": "lobstr",
    "path": "images/lobstr.svg",
    "url": "https://lobstr.r-lib.org"
  },
  {
    "name": "lubridate",
    "path": "images/lubridate.svg",
    "url": "https://lubridate.tidyverse.org"
  },
  {
    "name": "luz",
    "path": "images/luz.svg",
    "url": "https://mlverse.github.io/luz/"
  },
  {
    "name": "mall",
    "path": "images/mall.svg",
    "url": "https://mlverse.github.io/mall/"
  },
  {
    "name": "marquee",
    "path": "images/marquee.svg",
    "url": "https://marquee.r-lib.org"
  },
  {
    "name": "miniCRAN",
    "path": "images/miniCRAN.svg",
    "url": "https://andrie.github.io/miniCRAN/"
  },
  {
    "name": "modeldb",
    "path": "images/modeldb.svg",
    "url": "https://tidymodels.github.io/modeldb/"
  },
  {
    "name": "modelr",
    "path": "images/modelr.svg",
    "url": "https://modelr.tidyverse.org"
  },
  {
    "name": "multilevelmod",
    "path": "images/multilevelmod.svg",
    "url": "https://multilevelmod.tidymodels.org"
  },
  {
    "name": "odbc",
    "path": "images/odbc.svg",
    "url": "https://odbc.r-dbi.org"
  },
  {
    "name": "orbital",
    "path": "images/orbital.svg",
    "url": "https://orbital.tidymodels.org"
  },
  {
    "name": "pagedown",
    "path": "images/pagedown.svg",
    "url": "https://pagedown.rbind.io"
  },
  {
    "name": "parsnip",
    "path": "images/parsnip.svg",
    "url": "https://parsnip.tidymodels.org"
  },
  {
    "name": "patchwork",
    "path": "images/patchwork.svg",
    "url": "https://patchwork.data-imaginist.com"
  },
  {
    "name": "pins",
    "path": "images/pins.svg",
    "url": "https://pins.rstudio.com"
  },
  {
    "name": "pipe",
    "path": "images/pipe.svg",
    "url": "https://magrittr.tidyverse.org"
  },
  {
    "name": "pkgdown",
    "path": "images/pkgdown.svg",
    "url": "https://pkgdown.r-lib.org"
  },
  {
    "name": "plotnine",
    "path": "images/plotnine.svg",
    "url": "https://plotnine.org"
  },
  {
    "name": "plumber",
    "path": "images/plumber.svg",
    "url": "https://www.rplumber.io"
  },
  {
    "name": "plumber2",
    "path": "images/plumber2.svg",
    "url": "https://plumber2.posit.co/"
  },
  {
    "name": "plumbertableau",
    "path": "images/plumbertableau.svg",
    "url": "https://rstudio.github.io/plumbertableau/"
  },
  {
    "name": "pointblank",
    "path": "images/pointblank.svg",
    "url": "https://rstudio.github.io/pointblank/"
  },
  {
    "name": "poissonreg",
    "path": "images/poissonreg.svg",
    "url": "https://poissonreg.tidymodels.org"
  },
  {
    "name": "positron",
    "path": "images/positron.svg",
    "url": "https://positron.posit.co"
  },
  {
    "name": "probably",
    "path": "images/probably.svg",
    "url": "https://probably.tidymodels.org"
  },
  {
    "name": "promises",
    "path": "images/promises.svg",
    "url": "https://rstudio.github.io/promises/"
  },
  {
    "name": "purrr",
    "path": "images/purrr.svg",
    "url": "https://purrr.tidyverse.org"
  },
  {
    "name": "quarto",
    "path": "images/quarto.svg",
    "url": "https://quarto.org"
  },
  {
    "name": "r2d3",
    "path": "images/r2d3.svg",
    "url": "https://rstudio.github.io/r2d3/"
  },
  {
    "name": "ragg",
    "path": "images/ragg.svg",
    "url": "https://ragg.r-lib.org"
  },
  {
    "name": "rapp",
    "path": "images/rapp.svg",
    "url": "https://github.com/r-lib/Rapp"
  },
  {
    "name": "reactlog",
    "path": "images/reactlog.svg",
    "url": "https://rstudio.github.io/reactlog/"
  },
  {
    "name": "readr",
    "path": "images/readr.svg",
    "url": "https://readr.tidyverse.org"
  },
  {
    "name": "readxl",
    "path": "images/readxl.svg",
    "url": "https://readxl.tidyverse.org"
  },
  {
    "name": "recipes",
    "path": "images/recipes.svg",
    "url": "https://recipes.tidymodels.org"
  },
  {
    "name": "renv",
    "path": "images/renv.svg",
    "url": "https://rstudio.github.io/renv/"
  },
  {
    "name": "reprex",
    "path": "images/reprex.svg",
    "url": "https://reprex.tidyverse.org"
  },
  {
    "name": "reticulate",
    "path": "images/reticulate.svg",
    "url": "https://rstudio.github.io/reticulate/"
  },
  {
    "name": "rlang",
    "path": "images/rlang.svg",
    "url": "https://rlang.r-lib.org"
  },
  {
    "name": "rmarkdown",
    "path": "images/rmarkdown.svg",
    "url": "https://rmarkdown.rstudio.com"
  },
  {
    "name": "roxygen2",
    "path": "images/roxygen2.svg",
    "url": "https://roxygen2.r-lib.org"
  },
  {
    "name": "rray",
    "path": "images/rray.svg",
    "url": "https://rray.r-lib.org"
  },
  {
    "name": "rrd",
    "path": "images/rrd.svg",
    "url": "https://andrie.github.io/rrd/"
  },
  {
    "name": "rsample",
    "path": "images/rsample.svg",
    "url": "https://rsample.tidymodels.org"
  },
  {
    "name": "rsconnect",
    "path": "images/rsconnect.svg",
    "url": "https://rstudio.github.io/rsconnect/"
  },
  {
    "name": "rstudioapi",
    "path": "images/rstudioapi.svg",
    "url": "https://rstudio.github.io/rstudioapi/"
  },
  {
    "name": "rticles",
    "path": "images/rticles.svg",
    "url": "https://pkgs.rstudio.com/rticles/"
  },
  {
    "name": "rules",
    "path": "images/rules.svg",
    "url": "https://rules.tidymodels.org"
  },
  {
    "name": "rvest",
    "path": "images/rvest.svg",
    "url": "https://rvest.tidyverse.org"
  },
  {
    "name": "rwasm",
    "path": "images/rwasm.svg",
    "url": "https://r-wasm.github.io/rwasm/"
  },
  {
    "name": "sass",
    "path": "images/sass.svg",
    "url": "https://rstudio.github.io/sass/"
  },
  {
    "name": "scales",
    "path": "images/scales.svg",
    "url": "https://scales.r-lib.org"
  },
  {
    "name": "shiny",
    "path": "images/shiny.svg",
    "url": "https://shiny.posit.co"
  },
  {
    "name": "shinychat",
    "path": "images/shinychat.svg",
    "url": "https://posit-dev.github.io/shinychat/"
  },
  {
    "name": "shinytest2",
    "path": "images/shinytest2.svg",
    "url": "https://rstudio.github.io/shinytest2/"
  },
  {
    "name": "siuba",
    "path": "images/siuba.svg",
    "url": "https://siuba.org"
  },
  {
    "name": "sloop",
    "path": "images/sloop.svg",
    "url": "https://sloop.r-lib.org"
  },
  {
    "name": "sortable",
    "path": "images/sortable.svg",
    "url": "https://rstudio.github.io/sortable/"
  },
  {
    "name": "sparklyr",
    "path": "images/sparklyr.svg",
    "url": "https://spark.rstudio.com"
  },
  {
    "name": "sparsevctrs",
    "path": "images/sparsevctrs.png",
    "url": "https://r-lib.github.io/sparsevctrs/"
  },
  {
    "name": "spatialsample",
    "path": "images/spatialsample.svg",
    "url": "https://spatialsample.tidymodels.org"
  },
  {
    "name": "sss",
    "path": "images/sss.svg",
    "url": "https://andrie.github.io/sss/"
  },
  {
    "name": "stacks",
    "path": "images/stacks.svg",
    "url": "https://stacks.tidymodels.org"
  },
  {
    "name": "stringr",
    "path": "images/stringr.svg",
    "url": "https://stringr.tidyverse.org"
  },
  {
    "name": "svglite",
    "path": "images/svglite.svg",
    "url": "https://svglite.r-lib.org"
  },
  {
    "name": "systemfonts",
    "path": "images/systemfonts.svg",
    "url": "https://systemfonts.r-lib.org"
  },
  {
    "name": "tensorflow",
    "path": "images/tensorflow.svg",
    "url": "https://tensorflow.rstudio.com"
  },
  {
    "name": "testthat",
    "path": "images/testthat.svg",
    "url": "https://testthat.r-lib.org"
  },
  {
    "name": "textrecipes",
    "path": "images/textrecipes.svg",
    "url": "https://textrecipes.tidymodels.org"
  },
  {
    "name": "themis",
    "path": "images/themis.svg",
    "url": "https://themis.tidymodels.org"
  },
  {
    "name": "tibble",
    "path": "images/tibble.svg",
    "url": "https://tibble.tidyverse.org"
  },
  {
    "name": "tidyclust",
    "path": "images/tidyclust.svg",
    "url": "https://tidyclust.tidymodels.org"
  },
  {
    "name": "tidymodels",
    "path": "images/tidymodels.svg",
    "url": "https://tidymodels.tidymodels.org"
  },
  {
    "name": "tidyposterior",
    "path": "images/tidyposterior.svg",
    "url": "https://tidyposterior.tidymodels.org"
  },
  {
    "name": "tidypredict",
    "path": "images/tidypredict.svg",
    "url": "https://tidypredict.tidymodels.org"
  },
  {
    "name": "tidyr",
    "path": "images/tidyr.svg",
    "url": "https://tidyr.tidyverse.org"
  },
  {
    "name": "tidyverse",
    "path": "images/tidyverse.svg",
    "url": "https://tidyverse.tidyverse.org"
  },
  {
    "name": "torch",
    "path": "images/torch.svg",
    "url": "https://torch.mlverse.org"
  },
  {
    "name": "tune",
    "path": "images/tune.svg",
    "url": "https://tune.tidymodels.org"
  },
  {
    "name": "usethis",
    "path": "images/usethis.svg",
    "url": "https://usethis.r-lib.org"
  },
  {
    "name": "vctrs",
    "path": "images/vctrs.svg",
    "url": "https://vctrs.r-lib.org"
  },
  {
    "name": "vetiver",
    "path": "images/vetiver.svg",
    "url": "https://vetiver.posit.co"
  },
  {
    "name": "webr",
    "path": "images/webr.svg",
    "url": "https://docs.r-wasm.org/webr/"
  },
  {
    "name": "withr",
    "path": "images/withr.svg",
    "url": "https://withr.r-lib.org"
  },
  {
    "name": "workflows",
    "path": "images/workflows.svg",
    "url": "https://workflows.tidymodels.org"
  },
  {
    "name": "xaringan",
    "path": "images/xaringan.svg",
    "url": "https://github.com/yihui/xaringan"
  },
  {
    "name": "yardstick",
    "path": "images/yardstick.svg",
    "url": "https://yardstick.tidymodels.org"
  }
];
